version: '3.7'

services:
  weeping_front:
    build: 
      context: ./front/weeping/
      dockerfile: Dockerfile
    image: weeping_front:1.0
    ports: 
      - "${FRONT_PORT}:80"
    environment: 
       PRODUCTION: true
       BACK_PORT: ${BACK_PORT}
    depends_on: 
      - weeping_back

  weeping_back:
    build:
      context: ./back/weeping
      dockerfile: Dockerfile
    environment: 
      - port: 1337
    image: weeping_back:1.0
    ports: 
      - "${BACK_PORT}:1337"
    volumes:
      - .:/usr/src/app
  