version: '3.2'

services:
  weeping_front:
    #labels: 
    #  com.ambert.weeping.description:"Gestion des informations de la FFTT"
    build: 
      context: ./front/weeping/
      dockerfile: Dockerfile
    image: weeping_front:1.0
    ports: 
      - "5000:80"
    environment: 
      PRODUCTION: 'true'
  