export default{
    name:"WeePing",
    alt:"WeePing Application for Table Tennis players",
    logo:"/static/m.png",
    dev:{
        name:"Jean-Christophe Ambert",
        avatar:"/static/avatar/me.jpg",
        github:"https://github.com/jcambert/weeping",
        mail:"jc.ambert@gmail.com",
    },
    service:{
        url:'http://{host}:1337/api/v1/',
        api:{
            login:{
                verb:'post',
                url:'spid/login'
            },
            retrieveLicencieInfo:{
                verb:'get',
                url:'user-info/{licence}'
            },
            clubinfo:{
                verb:'get',
                url:'club-info/{club}'
            },
            joueurinfo:{
                verb:'get',
                url:'joueur-info/{licence}'
            },
            equipes:{
                verb:'get',
                url:'equipes/{type}/{club}'
            },
            classementequipe:{
                verb:'get',
                url:'resultat-equipe/{cx_poule}/{d1}/classement'
            },
            resultatequipe:{
                verb:'get',
                url:'resultat-equipe/{cx_poule}/{d1}/'
            },
            detailrencontre:{
                verb:'get',
                url:'detail-rencontre/{is_retour}/{phase}/{res_1}/{res_2}/{renc_id}/{equip_1}/{equip_2}/{equip_id1}/{equip_id2}'
            },
            joueurparties:{
                verb:'get',
                url:'joueur-parties/{licence}'
            }
        }
    }

}